version: "3"

services:

  postgres15_svce:
    image: postgres:15
    container_name: postgres15_cn
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - crm_postgres_data:/var/lib/postgresql/data

volumes:
  crm_postgres_data: {}
