version: "3"

services:

  postgres15:
    image: postgres:15
    container_name: postgres15
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data_crm:/var/lib/postgresql/data

volumes:
  postgres_data_crm: {}
